//------------------------------------------------------------------------------
// <wsdl2code-generated>
// This code was generated by http://www.wsdl2code.com iPhone version 2.1
// Date Of Creation: 6/8/2017 7:27:15 PM
//
//  Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code Version
//

#import <Foundation/Foundation.h>


@interface EnterpriseUser : NSObject
{
}
@property BOOL autorized;
@property BOOL autorizedSpecified;
@property (nonatomic, copy) NSString *firstName;
@property (nonatomic, copy) NSString *lastName;
@property (nonatomic, copy) NSString *enterpriseIdList;
@property (nonatomic, copy) NSString *accessLevels;
@property (nonatomic, copy) NSString *email;
@property (nonatomic, copy) NSString *hostName;
@property (nonatomic, copy) NSString *userLogin;
@property (nonatomic, copy) NSString *userPassword;
@property (nonatomic, copy) NSString *userCompanyName;
@property (nonatomic, copy) NSString *userNodeIds;
@property int userId;
@property BOOL userIdSpecified;

-(NSString*)toString:(BOOL)addNameWrap;
-(id)initWithArray:(NSArray*)array;
-(void)encodeWithCoder:(NSCoder *)encoder;
-(id)copyWithZone:(NSZone *)zone;
-(id)initWithCoder:(NSCoder *)decoder;
@end
