//------------------------------------------------------------------------------
// <wsdl2code-generated>
// This code was generated by http://www.wsdl2code.com iPhone version 2.1
// Date Of Creation: 8/22/2017 4:33:35 PM
//
//  Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code Version
//

#import <Foundation/Foundation.h>
#import "xpathquery.h"
#import "OrderService.h"

#ifndef _Wsdl2CodeProxyDelegate
#define _Wsdl2CodeProxyDelegate
@protocol Wsdl2CodeProxyDelegate
//if service recieve an error this method will be called
-(void)proxyRecievedError:(NSException*)ex InMethod:(NSString*)method;
//proxy finished, (id)data is the object of the relevant method service
-(void)proxydidFinishLoadingData:(id)data InMethod:(NSString*)method;
@end
#endif

@interface OrderServiceProxy : NSObject
@property (nonatomic,assign) id<Wsdl2CodeProxyDelegate> proxyDelegate;
@property (nonatomic,copy)   NSString* url;
@property (nonatomic,retain) OrderService* service;

-(id)initWithUrl:(NSString*)url AndDelegate:(id<Wsdl2CodeProxyDelegate>)delegate;
///Origin Return Type:NSString
-(void)GetOtherPaymentsJson:(NSString *)paramInfo ;
///Origin Return Type:NSString
-(void)CreateCheck:(NSString *)checkParamInfo ;
///Origin Return Type:NSString
-(void)CreateCheckJson:(NSString *)checkParamInfo ;
///Origin Return Type:NSString
-(void)CheckLinkAlive:(NSString *)paramInfo ;
///Origin Return Type:NSString
-(void)CheckLinkAliveJson:(NSString *)paramInfo ;
///Origin Return Type:NSString
-(void)GetItems:(NSString *)itemParamInfo ;
///Origin Return Type:NSString
-(void)GetItemsJson:(NSString *)itemParamInfo ;
///Origin Return Type:NSString
-(void)GetGroups:(NSString *)paramInfo ;
///Origin Return Type:NSString
-(void)GetGroupsJson:(NSString *)paramInfo ;
///Origin Return Type:NSString
-(void)GetCategories:(NSString *)paramInfo ;
///Origin Return Type:NSString
-(void)GetCategoriesJson:(NSString *)paramInfo ;
///Origin Return Type:NSString
-(void)GetSizes:(NSString *)paramInfo ;
///Origin Return Type:NSString
-(void)GetSizesJson:(NSString *)paramInfo ;
///Origin Return Type:NSString
-(void)GetPanels:(NSString *)paramInfo ;
///Origin Return Type:NSString
-(void)GetPanelsJson:(NSString *)paramInfo ;
///Origin Return Type:NSString
-(void)GetOtherPayments:(NSString *)paramInfo ;
@end
