//------------------------------------------------------------------------------
// <wsdl2code-generated>
// This code was generated by http://www.wsdl2code.com iPhone version 2.1
// Date Of Creation: 8/22/2017 4:33:35 PM
//
//  Please dont change this code, regeneration will override your changes
//</wsdl2code-generated>
//
//------------------------------------------------------------------------------
//
//This source code was auto-generated by Wsdl2Code Version
//

#import <Foundation/Foundation.h>
#import "OrderService_Enums.h"


@interface OrderService : NSObject
{
}
@property SoapProtocolVersion soapVersion;
@property BOOL allowAutoRedirect;
@property BOOL enableDecompression;
@property (nonatomic, copy) NSString *userAgent;
@property BOOL unsafeAuthenticatedConnectionSharing;
@property BOOL useDefaultCredentials;
@property (nonatomic, copy) NSString *connectionGroupName;
@property BOOL preAuthenticate;
@property (nonatomic, copy) NSString *url;
@property int timeout;
@property (nonatomic, assign) void(*targetAction)(id target,id sender,NSString* xml);
@property (nonatomic,assign) id actionDelegate;
@property (nonatomic, strong) NSURLConnection *wsConnection;
@property (nonatomic, strong) NSMutableData *webData;
@property (nonatomic, strong) NSError *error;
@property (nonatomic, strong) NSMutableDictionary *requestHeaders;
@property (nonatomic, copy)   NSString *eventName;

///Origin Return Type:NSString
-(void)GetOtherPaymentsJson:(NSString *)paramInfo ;
///Origin Return Type:NSString
-(void)CreateCheck:(NSString *)checkParamInfo ;
///Origin Return Type:NSString
-(void)CreateCheckJson:(NSString *)checkParamInfo ;
///Origin Return Type:NSString
-(void)CheckLinkAlive:(NSString *)paramInfo ;
///Origin Return Type:NSString
-(void)CheckLinkAliveJson:(NSString *)paramInfo ;
///Origin Return Type:NSString
-(void)GetItems:(NSString *)itemParamInfo ;
///Origin Return Type:NSString
-(void)GetItemsJson:(NSString *)itemParamInfo ;
///Origin Return Type:NSString
-(void)GetGroups:(NSString *)paramInfo ;
///Origin Return Type:NSString
-(void)GetGroupsJson:(NSString *)paramInfo ;
///Origin Return Type:NSString
-(void)GetCategories:(NSString *)paramInfo ;
///Origin Return Type:NSString
-(void)GetCategoriesJson:(NSString *)paramInfo ;
///Origin Return Type:NSString
-(void)GetSizes:(NSString *)paramInfo ;
///Origin Return Type:NSString
-(void)GetSizesJson:(NSString *)paramInfo ;
///Origin Return Type:NSString
-(void)GetPanels:(NSString *)paramInfo ;
///Origin Return Type:NSString
-(void)GetPanelsJson:(NSString *)paramInfo ;
///Origin Return Type:NSString
-(void)GetOtherPayments:(NSString *)paramInfo ;
-(id) initWithTarget:(id)target  AndAction:(void(*)(id target,id sender ,NSString* xml))action;
-(void) addTarget:(id)target AndAction:(void(*)(id target,id sender ,NSString* xml))action;
@end
